tap "homebrew/bundle"
tap "homebrew/services"
tap "natesales/repo", "https://github.com/natesales/repo"
brew "ruby"
brew "asciidoctor"
brew "node"
brew "aws-amplify"
brew "awscli"
brew "bandwhich"
brew "bat"
brew "bottom"
brew "curl"
brew "eza"
brew "fd", args: ["HEAD"]
brew "fzf"
brew "gh"
brew "git"
brew "git-delta"
brew "glow"
brew "go"
brew "kubelogin"
brew "kubernetes-cli"
brew "lua"
brew "luajit"
brew "msgpack", args: ["HEAD"]
brew "utf8proc", args: ["HEAD"]
brew "neovim"
brew "nethogs"
brew "ollama", args: ["HEAD"]
brew "pnpm", link: false
brew "python@3.12"
brew "ripgrep", args: ["HEAD"]
brew "rust"
brew "starship", args: ["HEAD"]
brew "the_silver_searcher", args: ["HEAD"]
brew "tmux", args: ["HEAD"]
brew "tree-sitter", args: ["HEAD"]
brew "virtualenvwrapper"
brew "yarn"
brew "zellij", args: ["HEAD"]
brew "zoxide"
brew "natesales/repo/q"
cargo "create-tauri-app"
flatpak "com.spotify.Client"
flatpak "me.timschneeberger.GalaxyBudsClient"
flatpak "org.mozilla.vpn"
flatpak "org.telegram.desktop"
vscode "astro-build.astro-vscode"
vscode "augment.vscode-augment"
vscode "biomejs.biome"
vscode "continue.continue"
vscode "esbenp.prettier-vscode"
vscode "firefox-devtools.vscode-firefox-debug"
vscode "johnnymorganz.stylua"
vscode "ms-azuretools.vscode-docker"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vscode.vscode-typescript-next"
vscode "rvest.vs-code-prettier-eslint"
vscode "tabnine.tabnine-vscode"
vscode "xadillax.viml"
