# see `man dnf.conf` for defaults and possible options
[main]
#cacheonly=all
cacheonly=none
clean_requirements_on_remove=False
installonly_limit=4
keepcache=1
obsoletes=False
max_parallel_downloads=15
